certificateAuthorities:
  org2.example.com:
    tlsCACerts:
      path: /etc/firefly/organizations/peerOrganizations/org2.example.com/msp/tlscacerts/ca.crt
    url: https://ca_org2:8054
    grpcOptions:
      ssl-target-name-override: org2.example.com
    registrar:
      enrollId: admin
      enrollSecret: adminpw
channels:
  pm3:
    orderers:
      - fabric_orderer
    peers:
      fabric_peer:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
client:
  BCCSP:
    security:
      default:
        provider: SW
      enabled: true
      hashAlgorithm: SHA2
      level: 256
      softVerify: true
  credentialStore:
    cryptoStore:
      path: /etc/firefly/organizations/peerOrganizations/org2.example.com/msp
    path: /etc/firefly/organizations/peerOrganizations/org2.example.com/msp
  cryptoconfig:
    path: /etc/firefly/organizations/peerOrganizations/org2.example.com/msp
  logging:
    level: info
  organization: org2.example.com
  tlsCerts:
    client:
      cert:
        path: /etc/firefly/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem
      key:
        path: /etc/firefly/organizations/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/6b25f4b4bea4bec8b372ec9aedea93f12917227a04389159b689da80fb5a9c0f_sk
orderers:
  fabric_orderer:
    tlsCACerts:
      path: /etc/firefly/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/tlscacerts/tls-localhost-9054-ca-orderer.pem
    url: grpcs://orderer.example.com:7050
organizations:
  org2.example.com:
    certificateAuthorities:
      - org2.example.com
    cryptoPath: /tmp/msp
    mspid: Org2MSP
    peers:
      - fabric_peer
peers:
  fabric_peer:
    tlsCACerts:
      path: /etc/firefly/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/tlscacerts/tls-localhost-8054-ca-org2.pem
    url: grpcs://peer0.org2.example.com:9051
version: 1.1.0%
