#
# PM3 Package Chaincode - Kubernetes Deployment and Service
# For running as external service (CCAAS)
#

apiVersion: v1
kind: Namespace
metadata:
  name: chaincodes

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm3package
  namespace: chaincodes
  labels:
    app: pm3package
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pm3package
  template:
    metadata:
      labels:
        app: pm3package
    spec:
      containers:
      - name: pm3package
        image: pm3package:latest
        imagePullPolicy: Never  # Use pre-built image from kind registry
        ports:
        - name: chaincode
          containerPort: 7052
          protocol: TCP
        env:
        - name: CHAINCODE_ID
          value: "pm3package:1.0"
        - name: CHAINCODE_SERVER_ADDRESS
          value: "0.0.0.0:7052"
        - name: CORE_PEER_TLS_ENABLED
          value: "false"
        - name: DEBUG
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 7052
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 7052
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: pm3package
  namespace: chaincodes
  labels:
    app: pm3package
spec:
  selector:
    app: pm3package
  ports:
  - name: chaincode
    port: 7052
    targetPort: 7052
    protocol: TCP
  type: ClusterIP
